### PR TITLE
Remove Conflict about Reso Coder

### PR DESCRIPTION
**Pull request by Abhishek01039**
you have provided less information regarding the Reso coder
`Posts a lot of tutorials about Flutter` only this.

### CODE REVIEW

**Comment by FlutterTutorial** [comment]
Sorry. I didn't see the duplicate. I'll place the better description you've provided but I'm gonna have to remove  he doesn't have a lot of free time sweat_smile Yet he still manages to squeeze in tough workouts muscle

**Comment by Abhishek01039** [comment]
Hi @FlutterTutorial Thanks that you have removed duplicates.

**Comment by FlutterTutorial** [comment]
I just realized you've removed the duplicate and fixed it. Silly me. Sorry for not accepting your pull request. I already edited it before I realized it

**Comment by Abhishek01039** [comment]
No issue @FlutterTutorial

**Comment by Abhishek01039** [comment]
if you have any other plan then please message me in Discord.

**Pull request closed without merging**
